services:
  veterinariatfm-db:
    container_name: veterinariatfm-db
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_DATABASE: "veterinariatfm"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

volumes:
  mysql-data:
    external: false